apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingress.yaml
  - worker/deployment.yaml
  - frontend/rollout.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - frontend/analysis.yaml