apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: "Entorno dev - cloudops-store"
  sourceRepos:
    - "https://github.com/elbryan123blxd-ai/Proyecto-DevOps"
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  roles:
    - name: read-only
      description: "Lectura del proyecto dev"
      policies:
        - p, proj:dev:read-only, applications, get, dev/*, allow
      groups:
        - devs