apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops-store-dev
  namespace: argocd
spec:
  description: Proyecto dev - tienda cloudops-store
  sourceRepos:
    - https://github.com/elbryan123blxd-ai/Proyecto-DevOps
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
