apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops-store-prod
  namespace: argocd
spec:
  description: Proyecto prod - tienda en producción
  sourceRepos:
    - https://github.com/elbryan123blxd-ai/Proyecto-DevOps
  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
  syncWindows:
    - kind: allow
      schedule: "0 9-17 * * 1-5"
      duration: 8h
      applications:
        - cloudops-store-prod-*
