server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        # FASE B: broken - returns 502 for demo
        return 502;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}