apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-dev
  namespace: argocd
spec:
  project: cloudops-store-staging
  source:
    repoURL: https://github.com/elbryan123blxd-ai/Proyecto-DevOps
    targetRevision: HEAD
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
