apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  replicas: 3
  strategy:
    canary:
      # Análisis de métricas activo en prod: consulta Prometheus (Fase 5)
      analysis:
        templates:
          - templateName: cloudops-store-canary
        args:
          - name: service-name
            value: frontend-stable