apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: IMAGE-api
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-prod-api
    newTag: sha-e88cb20
  - name: IMAGE-worker
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-prod-worker
    newTag: sha-e88cb20
  - name: IMAGE-frontend
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-prod-frontend
    newTag: sha-e88cb20

patchesStrategicMerge:
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml