apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev
  namespace: argocd
spec:
  project: cloudops-store-dev
  source:
    repoURL: https://github.com/elbryan123blxd-ai/Proyecto-DevOps
    targetRevision: HEAD
    path: argocd/applications/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
