apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-store-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: prod
  source:
    repoURL: https://github.com/elbryan123blxd-ai/Proyecto-DevOps
    targetRevision: main
    path: argocd/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m