apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: IMAGE-api
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-dev-api
    newTag: sha-ca1cfa2
  - name: IMAGE-worker
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-dev-worker
    newTag: sha-ca1cfa2
  - name: IMAGE-frontend
    newName: 499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-dev-frontend
    newTag: sha-ca1cfa2

patchesStrategicMerge:
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml