apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=499503541876.dkr.ecr.us-east-1.amazonaws.com/cloudops-staging-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
spec:
  replicas: 2