apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cloudops-store-canary
  labels:
    app.kubernetes.io/part-of: cloudops-store
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 3
      provider:
        prometheus:
          # Prometheus real de kube-prometheus-stack (Fase 5, namespace monitoring)
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(
              rate(
                nginx_ingress_controller_requests{
                  namespace="prod",
                  ingress="frontend",
                  status!~"5.."
                }[2m]
              )
            )
            /
            sum(
              rate(
                nginx_ingress_controller_requests{
                  namespace="prod",
                  ingress="frontend"
                }[2m]
              )
            ) * 100