resources:
  - ../../base
replicas:
  - name: cloudops-store
    count: 1
images:
  - name: cloudops-store-api
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cloudops-gym-api-dev
    newTag: latest
  - name: cloudops-store-frontend
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cloudops-gym-frontend-dev
    newTag: latest
configMapGenerator:
  - name: cloudops-config
    behavior: merge
    literals:
      - APP_ENV=dev
