name: CD - Build & Push ECR + GitOps (dev)

on:
  push:
    branches: [main]
    paths-ignore:
      - "argocd/**"
      - "terraform/**"
      - "docs/**"
      - "observability/**"
      - "CLAUDE.md"
      - "README.md"

permissions:
  id-token: write
  contents: write

concurrency:
  group: cd-main
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "499503541876"
  ECR_REGISTRY: 499503541876.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    name: Build & push + promover GitOps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          debug: true

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir tag de imagen
        id: tag
        run: echo "image_tag=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: app/api
          push: true
          tags: ${{ env.ECR_REGISTRY }}/cloudops-dev-api:${{ steps.tag.outputs.image_tag }}

      - name: Build & push Worker
        uses: docker/build-push-action@v6
        with:
          context: app/worker
          push: true
          tags: ${{ env.ECR_REGISTRY }}/cloudops-dev-worker:${{ steps.tag.outputs.image_tag }}

      - name: Build & push Frontend
        uses: docker/build-push-action@v6
        with:
          context: app/frontend
          push: true
          tags: ${{ env.ECR_REGISTRY }}/cloudops-dev-frontend:${{ steps.tag.outputs.image_tag }}

      - name: Actualizar tag en overlay de dev
        run: |
          sed -i "s|newTag: .*|newTag: ${{ steps.tag.outputs.image_tag }}|" argocd/overlays/dev/kustomization.yaml

      - name: ¿Cambió la versión en el overlay de dev?
        id: diff
        run: |
          if git diff --quiet argocd/overlays/dev/kustomization.yaml; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit GitOps (promover tag en dev)
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add argocd/overlays/dev/kustomization.yaml
          git commit -m "chore(gitops): promover ${{ steps.tag.outputs.image_tag }} a dev"
          git push origin HEAD:main